version: 2.1

commands:
  setup:
    description: Basic steps to install packages, lint, prettier, and build
    steps:
      - checkout
      - run:
          name: Get App Name
          command: |
            echo 'export APP_NAME="$(partial=${CIRCLE_PROJECT_REPONAME/.$DOKKU_BASE_DOMAIN/''} && echo ${partial/$DOKKU_BASE_DOMAIN/'main'})"' >> $BASH_ENV
            echo "Found app name: $(partial=${CIRCLE_PROJECT_REPONAME/.$DOKKU_BASE_DOMAIN/''} && echo ${partial/$DOKKU_BASE_DOMAIN/'main'})"
      - run:
          name: Versions
          command: |
            echo "Yarn: $(yarn -v)" && echo "Node: $(node -v)" && echo "NPM: $(npm -v)"
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
            - v3-dependencies-
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier
          command: yarn prettier:check
      - run:
          name: Build
          command: yarn build
      - save_cache:
          paths:
            - ./node_modules
            - ./.next/cache
          key: v3-dependencies-{{ checksum "yarn.lock" }}

jobs:
  all:
    docker:
      - image: circleci/node:10.17
    working_directory: ~/repo
    steps:
      - setup
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  all:
    jobs:
      - all:
          context: common-env-vars
          filters:
            branches:
              ignore:
                - master
                - gh-pages
